/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddFriends: typeof import('./components/modules/AddFriends/AddFriends.vue')['default']
    AuthLayout: typeof import('./components/UI/AuthLayout/AuthLayout.vue')['default']
    Congratulations: typeof import('./components/modules/Congratulations/Congratulations.vue')['default']
    Feed: typeof import('./components/modules/Feed/Feed.vue')['default']
    FeedCard: typeof import('./components/modules/Feed/FeedCard.vue')['default']
    FeedSidebarNav: typeof import('./components/modules/Feed/FeedSidebarNav.vue')['default']
    FeedTopHeader: typeof import('./components/modules/Feed/FeedTopHeader.vue')['default']
    FeedTrendsPanel: typeof import('./components/modules/Feed/FeedTrendsPanel.vue')['default']
    InputLabel: typeof import('./components/UI/inputLabel/InputLabel.vue')['default']
    Interest: typeof import('./components/modules/interest/Interest.vue')['default']
    LanguageSwitcher: typeof import('./components/LanguageSwitcher.vue')['default']
    Login: typeof import('./components/modules/Login/Login.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Signup: typeof import('./components/modules/Signup/Signup.vue')['default']
    Snackbar: typeof import('./components/UI/Snackbar/Snackbar.vue')['default']
  }
}
