/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddFriends: typeof import('./components/modules/AddFriends/AddFriends.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppLoader: typeof import('./components/UI/AppLoader/AppLoader.vue')['default']
    AuthLayout: typeof import('./components/UI/AuthLayout/AuthLayout.vue')['default']
    CommentsDrawer: typeof import('./components/modules/Feed/CommentsDrawer.vue')['default']
    Congratulations: typeof import('./components/modules/Congratulations/Congratulations.vue')['default']
    ErrorBoundary: typeof import('./components/UI/ErrorBoundary/ErrorBoundary.vue')['default']
    EventDetails: typeof import('./components/modules/Feed/EventDetails.vue')['default']
    EventSearchAutocomplete: typeof import('./components/modules/Feed/EventSearchAutocomplete.vue')['default']
    EventView: typeof import('./components/modules/Feed/EventView.vue')['default']
    Feed: typeof import('./components/modules/Feed/Feed.vue')['default']
    FeedCard: typeof import('./components/modules/Feed/FeedCard.vue')['default']
    FeedCardStandalone: typeof import('./components/FeedCardStandalone.vue')['default']
    FeedSidebarNav: typeof import('./components/modules/Feed/FeedSidebarNav.vue')['default']
    FeedTopHeader: typeof import('./components/modules/Feed/FeedTopHeader.vue')['default']
    FeedTrendsPanel: typeof import('./components/modules/Feed/FeedTrendsPanel.vue')['default']
    InlineComments: typeof import('./components/modules/Feed/InlineComments.vue')['default']
    InputLabel: typeof import('./components/UI/inputLabel/InputLabel.vue')['default']
    Interest: typeof import('./components/modules/interest/Interest.vue')['default']
    LandingPage: typeof import('./components/modules/Landingpage/LandingPage.vue')['default']
    LanguageSwitcher: typeof import('./components/LanguageSwitcher.vue')['default']
    Login: typeof import('./components/modules/Login/Login.vue')['default']
    LoginRequiredDialog: typeof import('./components/UI/LoginRequiredDialog/LoginRequiredDialog.vue')['default']
    Profile: typeof import('./components/modules/Profile/Profile.vue')['default']
    RequestPassword: typeof import('./components/modules/PasswordRecovery/RequestPassword.vue')['default']
    ResetPassword: typeof import('./components/modules/PasswordRecovery/ResetPassword.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./components/UI/SearchInput/SearchInput.vue')['default']
    SelectableChip: typeof import('./components/UI/SelectableChip/SelectableChip.vue')['default']
    ShareSheet: typeof import('./components/modules/UI/ShareSheet/ShareSheet.vue')['default']
    Signup: typeof import('./components/modules/Signup/Signup.vue')['default']
    Snackbar: typeof import('./components/UI/Snackbar/Snackbar.vue')['default']
    SocialAuthButtons: typeof import('./components/UI/SocialAuthButtons/SocialAuthButtons.vue')['default']
    VerifyPin: typeof import('./components/modules/PasswordRecovery/VerifyPin.vue')['default']
  }
}
