/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/home/': RouteRecordInfo<'/home/', '/home', Record<never, never>, Record<never, never>>,
    '/private/AddFriends': RouteRecordInfo<'/private/AddFriends', '/private/AddFriends', Record<never, never>, Record<never, never>>,
    '/private/feed': RouteRecordInfo<'/private/feed', '/private/feed', Record<never, never>, Record<never, never>>,
    '/private/Interest': RouteRecordInfo<'/private/Interest', '/private/Interest', Record<never, never>, Record<never, never>>,
    '/private/test-auth': RouteRecordInfo<'/private/test-auth', '/private/test-auth', Record<never, never>, Record<never, never>>,
    '/public/ConfirmEmail': RouteRecordInfo<'/public/ConfirmEmail', '/public/ConfirmEmail', Record<never, never>, Record<never, never>>,
    '/public/Congratulations': RouteRecordInfo<'/public/Congratulations', '/public/Congratulations', Record<never, never>, Record<never, never>>,
    '/public/Interest': RouteRecordInfo<'/public/Interest', '/public/Interest', Record<never, never>, Record<never, never>>,
    '/public/Login': RouteRecordInfo<'/public/Login', '/public/Login', Record<never, never>, Record<never, never>>,
    '/public/RequestPassword': RouteRecordInfo<'/public/RequestPassword', '/public/RequestPassword', Record<never, never>, Record<never, never>>,
    '/public/ResetPassword': RouteRecordInfo<'/public/ResetPassword', '/public/ResetPassword', Record<never, never>, Record<never, never>>,
    '/public/Signup': RouteRecordInfo<'/public/Signup', '/public/Signup', Record<never, never>, Record<never, never>>,
    '/public/VerifyPin': RouteRecordInfo<'/public/VerifyPin', '/public/VerifyPin', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/home/index.vue': {
      routes: '/home/'
      views: never
    }
    'src/pages/private/AddFriends.vue': {
      routes: '/private/AddFriends'
      views: never
    }
    'src/pages/private/feed.vue': {
      routes: '/private/feed'
      views: never
    }
    'src/pages/private/Interest.vue': {
      routes: '/private/Interest'
      views: never
    }
    'src/pages/private/test-auth.vue': {
      routes: '/private/test-auth'
      views: never
    }
    'src/pages/public/ConfirmEmail.vue': {
      routes: '/public/ConfirmEmail'
      views: never
    }
    'src/pages/public/Congratulations.vue': {
      routes: '/public/Congratulations'
      views: never
    }
    'src/pages/public/Interest.vue': {
      routes: '/public/Interest'
      views: never
    }
    'src/pages/public/Login.vue': {
      routes: '/public/Login'
      views: never
    }
    'src/pages/public/RequestPassword.vue': {
      routes: '/public/RequestPassword'
      views: never
    }
    'src/pages/public/ResetPassword.vue': {
      routes: '/public/ResetPassword'
      views: never
    }
    'src/pages/public/Signup.vue': {
      routes: '/public/Signup'
      views: never
    }
    'src/pages/public/VerifyPin.vue': {
      routes: '/public/VerifyPin'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
