/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/event/[id]': RouteRecordInfo<'/event/[id]', '/event/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/feed': RouteRecordInfo<'/feed', '/feed', Record<never, never>, Record<never, never>>,
    '/profile/': RouteRecordInfo<'/profile/', '/profile', Record<never, never>, Record<never, never>>,
    '/profile/[id]': RouteRecordInfo<'/profile/[id]', '/profile/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/add-friends': RouteRecordInfo<'/add-friends', '/add-friends', Record<never, never>, Record<never, never>>,
    '/confirm-email': RouteRecordInfo<'/confirm-email', '/confirm-email', Record<never, never>, Record<never, never>>,
    '/congratulations': RouteRecordInfo<'/congratulations', '/congratulations', Record<never, never>, Record<never, never>>,
    '/explore': RouteRecordInfo<'/explore', '/explore', Record<never, never>, Record<never, never>>,
    '/interest': RouteRecordInfo<'/interest', '/interest', Record<never, never>, Record<never, never>>,
    '/interests/[slug]': RouteRecordInfo<'/interests/[slug]', '/interests/:slug', { slug: ParamValue<true> }, { slug: ParamValue<false> }>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/request-password': RouteRecordInfo<'/request-password', '/request-password', Record<never, never>, Record<never, never>>,
    '/reset-password': RouteRecordInfo<'/reset-password', '/reset-password', Record<never, never>, Record<never, never>>,
    '/signup': RouteRecordInfo<'/signup', '/signup', Record<never, never>, Record<never, never>>,
    '/updates': RouteRecordInfo<'/updates', '/updates', Record<never, never>, Record<never, never>>,
    '/verify-pin': RouteRecordInfo<'/verify-pin', '/verify-pin', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/(private)/event/[id].vue': {
      routes: '/event/[id]'
      views: never
    }
    'src/pages/(private)/feed.vue': {
      routes: '/feed'
      views: never
    }
    'src/pages/(private)/profile/index.vue': {
      routes: '/profile/'
      views: never
    }
    'src/pages/(private)/profile/[id].vue': {
      routes: '/profile/[id]'
      views: never
    }
    'src/pages/(public)/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/(public)/add-friends.vue': {
      routes: '/add-friends'
      views: never
    }
    'src/pages/(public)/confirm-email.vue': {
      routes: '/confirm-email'
      views: never
    }
    'src/pages/(public)/congratulations.vue': {
      routes: '/congratulations'
      views: never
    }
    'src/pages/(public)/explore.vue': {
      routes: '/explore'
      views: never
    }
    'src/pages/(public)/interest.vue': {
      routes: '/interest'
      views: never
    }
    'src/pages/(public)/interests/[slug].vue': {
      routes: '/interests/[slug]'
      views: never
    }
    'src/pages/(public)/login.vue': {
      routes: '/login'
      views: never
    }
    'src/pages/(public)/request-password.vue': {
      routes: '/request-password'
      views: never
    }
    'src/pages/(public)/reset-password.vue': {
      routes: '/reset-password'
      views: never
    }
    'src/pages/(public)/signup.vue': {
      routes: '/signup'
      views: never
    }
    'src/pages/(public)/updates.vue': {
      routes: '/updates'
      views: never
    }
    'src/pages/(public)/verify-pin.vue': {
      routes: '/verify-pin'
      views: never
    }
    'src/pages/[...all].vue': {
      routes: '/[...all]'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
